CREATE TABLE BOARD(
	ID VARCHAR(20),
	PW VARCHAR(20),
	NAME VARCHAR(20)
);
desc board;
INSERT INTO BOARD VALUES('user' , 'user1' , '강호동');
DELETE FROM BOARD WHERE ID = 'user';
SELECT * FROM BOARD;